parameters:
  env(JOBBOY_REDIS_HOST): ''
  env(JOBBOY_REDIS_PORT): ''

job_boy:
  process_repository:
    name: redis
    host: '%env(resolve:JOBBOY_REDIS_HOST)%'
    port: '%env(resolve:JOBBOY_REDIS_PORT)%'

#  process_repository: doctrine
#  process_repository: in_memory

#  process_class: JobBoy\Process\Domain\Entity\Infrastructure\TouchCallback\HydratableProcess

#  api:
#    required_role: IS_AUTHENTICATED_ANONYMOUSLY
