parameters:
  env(JOBBOY_REDIS_HOST): ''

job_boy:
  process_repository: redis
#  process_repository: doctrine

#  process_class: JobBoy\Process\Domain\Entity\Infrastructure\TouchCallback\HydratableProcess

  redis:
    host: '%env(resolve:JOBBOY_REDIS_HOST)%'
    port: '%env(resolve:JOBBOY_REDIS_PORT)%'
