controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

jobboy:
    resource: ../../vendor/dansan/jobboy-api/src/JobBoy/Process/Api/Controller/
    type: annotation
