services:

  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  JobBoyExample\Jobs\CreateDataFile\Initialize:
    class: JobBoyExample\Jobs\CreateDataFile\Initialize
    arguments:
      $workingDir: "@jobboy.create_data_file.working_dir"
    lazy: true
    tags:
      - name: jobboy.process_handler

  JobBoyExample\Jobs\CreateDataFile\Iterate:
    class: JobBoyExample\Jobs\CreateDataFile\Iterate
    lazy: true
    tags:
      - name: jobboy.process_handler


  JobBoyExample\Jobs\CreateDataFile\Finalize:
    class: JobBoyExample\Jobs\CreateDataFile\Finalize
    lazy: true
    tags:
      - name: jobboy.process_handler

  JobBoyExample\Jobs\CreateDataFile\Fail:
    class: JobBoyExample\Jobs\CreateDataFile\Fail
    lazy: true
    tags:
      - name: jobboy.process_handler
