services:

  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  App\JobBoy\Common\FreeHandled:
    class: App\JobBoy\Common\FreeHandled
    lazy: true
    tags:
      - name: jobboy.process_handler
        priority: 110


  JobBoy\Process\Domain\ProcessHandler\ProcessHandlers\Common\Dummy:
    class: JobBoy\Process\Domain\ProcessHandler\ProcessHandlers\Common\Dummy
    lazy: true
    tags:
      - name: jobboy.process_handler
        priority: 120

